TYPO3:
  Neos:
    userInterface:
      requireJsPathMapping:
        'Sandstorm.ContentComments': 'resource://Sandstorm.ContentComments/Public/JavaScript/'

    typoScript:
      autoInclude:
        'Sandstorm.ContentComments': TRUE
